--
-- PostgreSQL database dump
--

\restrict g7gNBYudD88oOAbyd4TewXfwYb4lTpeYszAN9E0AKTV81f0YVqg6xrygFgRtd9Q

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attestat-result-otchen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."attestat-result-otchen" (
    id_rec integer NOT NULL,
    id_otchet integer NOT NULL,
    id_attest integer NOT NULL,
    id_result integer NOT NULL,
    date_zapolneniya date NOT NULL,
    dnevnic_ocenka integer NOT NULL,
    otchet_ocenka integer NOT NULL,
    recomendation text NOT NULL,
    itog_ocenka integer NOT NULL,
    status_res character varying(50) NOT NULL,
    date_res date NOT NULL,
    id_vypol integer NOT NULL,
    type_otchet character varying(50) NOT NULL,
    date_napisanie date NOT NULL,
    soderzhanie text NOT NULL,
    id_xar integer NOT NULL,
    id_kom integer NOT NULL,
    CONSTRAINT "attestat-result-otchen_dnevnic_ocenka_check" CHECK (((dnevnic_ocenka >= 2) AND (dnevnic_ocenka <= 5))),
    CONSTRAINT "attestat-result-otchen_itog_ocenka_check" CHECK (((itog_ocenka >= 2) AND (itog_ocenka <= 5))),
    CONSTRAINT "attestat-result-otchen_otchet_ocenka_check" CHECK (((otchet_ocenka >= 2) AND (otchet_ocenka <= 5)))
);


ALTER TABLE public."attestat-result-otchen" OWNER TO postgres;

--
-- Name: attestat-result-otchen_id_rec_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."attestat-result-otchen" ALTER COLUMN id_rec ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."attestat-result-otchen_id_rec_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: curator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.curator (
    id_curator integer NOT NULL,
    id_organization integer NOT NULL,
    name_curator character varying(100),
    position_curator character varying(100),
    email_curator character varying(100)
);


ALTER TABLE public.curator OWNER TO postgres;

--
-- Name: curator_id_curator_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.curator ALTER COLUMN id_curator ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curator_id_curator_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: etap_plana; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etap_plana (
    id_etap integer NOT NULL,
    name_etap character varying(255) NOT NULL,
    stat_etap_date date NOT NULL,
    end_etap_date date NOT NULL,
    id_plan integer NOT NULL
);


ALTER TABLE public.etap_plana OWNER TO postgres;

--
-- Name: etap_plana_id_etap_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.etap_plana ALTER COLUMN id_etap ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.etap_plana_id_etap_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kaf - practika; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."kaf - practika" (
    id_kafedra integer NOT NULL,
    id_practika integer NOT NULL
);


ALTER TABLE public."kaf - practika" OWNER TO postgres;

--
-- Name: kafedra; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kafedra (
    id_kafedra integer NOT NULL,
    naimenovanie character varying(255) NOT NULL,
    facultet character varying(100) NOT NULL
);


ALTER TABLE public.kafedra OWNER TO postgres;

--
-- Name: kafedra_id_kafedra_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kafedra ALTER COLUMN id_kafedra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kafedra_id_kafedra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kom - kafedra; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."kom - kafedra" (
    id_kafedra integer NOT NULL,
    id_kom integer NOT NULL
);


ALTER TABLE public."kom - kafedra" OWNER TO postgres;

--
-- Name: komissiya; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.komissiya (
    id_kom integer NOT NULL,
    nazvamie_kom character varying(255) NOT NULL,
    predsedatel_name character varying(255) NOT NULL,
    date_zasedaniya date NOT NULL
);


ALTER TABLE public.komissiya OWNER TO postgres;

--
-- Name: komissiya_id_kom_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.komissiya ALTER COLUMN id_kom ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.komissiya_id_kom_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kompetenciya; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kompetenciya (
    id_kompetenciya integer NOT NULL,
    naimenovanie character varying(100) NOT NULL
);


ALTER TABLE public.kompetenciya OWNER TO postgres;

--
-- Name: kompetenciya_id_kompetenciya_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kompetenciya ALTER COLUMN id_kompetenciya ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kompetenciya_id_kompetenciya_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kompetenciya_studenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kompetenciya_studenta (
    id_studenta integer NOT NULL,
    id_kompetencii integer NOT NULL,
    uroven_znanii integer NOT NULL,
    CONSTRAINT kompetenciya_studenta_uroven_znanii_check CHECK (((uroven_znanii >= 1) AND (uroven_znanii <= 5)))
);


ALTER TABLE public.kompetenciya_studenta OWNER TO postgres;

--
-- Name: org - curator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."org - curator" (
    id_curator integer NOT NULL,
    id_organization integer NOT NULL
);


ALTER TABLE public."org - curator" OWNER TO postgres;

--
-- Name: org - practika; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."org - practika" (
    id_organization integer NOT NULL,
    id_practika integer NOT NULL
);


ALTER TABLE public."org - practika" OWNER TO postgres;

--
-- Name: organization; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organization (
    id_organization integer NOT NULL,
    name_organization character varying(150) NOT NULL,
    yur_adres character varying(255) NOT NULL
);


ALTER TABLE public.organization OWNER TO postgres;

--
-- Name: organization_id_organization_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.organization ALTER COLUMN id_organization ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_id_organization_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_praktiki; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plan_praktiki (
    id_plan integer NOT NULL,
    opisanie_plan text NOT NULL,
    grafik_plan text NOT NULL,
    id_practika integer NOT NULL,
    id_prepod integer NOT NULL,
    id_curator integer NOT NULL
);


ALTER TABLE public.plan_praktiki OWNER TO postgres;

--
-- Name: plan_praktiki_id_plan_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plan_praktiki ALTER COLUMN id_plan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_praktiki_id_plan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: practika; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.practika (
    id_practica integer NOT NULL,
    name_practika character varying(255) NOT NULL,
    type_praktiki character varying(255),
    start_date date NOT NULL,
    end_date date NOT NULL,
    prikas_number integer NOT NULL,
    id_prepod integer NOT NULL,
    id_curator integer NOT NULL
);


ALTER TABLE public.practika OWNER TO postgres;

--
-- Name: practika_id_practica_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.practika ALTER COLUMN id_practica ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.practika_id_practica_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prepodavatel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prepodavatel (
    id_prepod integer NOT NULL,
    id_kafedra integer NOT NULL,
    name_prepod character varying(100) NOT NULL,
    position_prepod character varying(100) NOT NULL,
    email_prepod character varying(100) NOT NULL
);


ALTER TABLE public.prepodavatel OWNER TO postgres;

--
-- Name: prepodavatel_id_prepod_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prepodavatel ALTER COLUMN id_prepod ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prepodavatel_id_prepod_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raspredelenie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.raspredelenie (
    id_raspred integer NOT NULL,
    id_student integer NOT NULL,
    id_prepod integer NOT NULL,
    id_zayavka integer NOT NULL,
    id_vacansiya integer NOT NULL,
    id_curator integer NOT NULL
);


ALTER TABLE public.raspredelenie OWNER TO postgres;

--
-- Name: sovpadenie_po_kompetencii; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sovpadenie_po_kompetencii (
    id_sovp integer NOT NULL,
    id_zayavki integer NOT NULL,
    id_kompetenciya integer NOT NULL,
    procent double precision NOT NULL,
    CONSTRAINT sovpadenie_po_kompetencii_procent_check CHECK (((procent >= (0)::double precision) AND (procent <= (100)::double precision)))
);


ALTER TABLE public.sovpadenie_po_kompetencii OWNER TO postgres;

--
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    id_studenta integer NOT NULL,
    name_student character varying(100) NOT NULL,
    id_kafedra integer NOT NULL,
    academiv_group character varying(50) NOT NULL,
    sredniy_ball numeric(3,2) NOT NULL,
    email_student character varying(255)
);


ALTER TABLE public.student OWNER TO postgres;

--
-- Name: student_id_studenta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN id_studenta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_studenta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trebovanie_vakansii; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trebovanie_vakansii (
    id_vakansii integer NOT NULL,
    id_kompetencii integer NOT NULL,
    trebuemyi_uroven integer NOT NULL,
    CONSTRAINT trebovanie_vakansii_trebuemyi_uroven_check CHECK (((trebuemyi_uroven >= 1) AND (trebuemyi_uroven <= 5)))
);


ALTER TABLE public.trebovanie_vakansii OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_user integer NOT NULL,
    login character varying(64) NOT NULL,
    password_hash character varying(256) NOT NULL,
    role character varying(32) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    id_studenta integer,
    id_prepod integer,
    id_curator integer,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['student'::character varying, 'curator'::character varying, 'teacher'::character varying, 'admin'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vakansiya; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vakansiya (
    id_vakansiya integer NOT NULL,
    id_organization integer NOT NULL,
    name_position character varying(100) NOT NULL,
    opisanie text NOT NULL,
    kolichestvo_mest integer NOT NULL,
    CONSTRAINT vakansiya_kolichestvo_mest_check CHECK ((kolichestvo_mest >= 0))
);


ALTER TABLE public.vakansiya OWNER TO postgres;

--
-- Name: vakansiya_id_vakansiya_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vakansiya ALTER COLUMN id_vakansiya ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vakansiya_id_vakansiya_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vypolnenie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vypolnenie (
    id_vyp integer NOT NULL,
    id_zad integer NOT NULL,
    status_vyp integer NOT NULL,
    date_naznach date NOT NULL,
    start_vyp_date date NOT NULL,
    end_vyp_date date NOT NULL
);


ALTER TABLE public.vypolnenie OWNER TO postgres;

--
-- Name: vypolnenie - at-res-otch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."vypolnenie - at-res-otch" (
    id_rec integer NOT NULL,
    id_vyp integer NOT NULL
);


ALTER TABLE public."vypolnenie - at-res-otch" OWNER TO postgres;

--
-- Name: vypolnenie - zadanie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."vypolnenie - zadanie" (
    id_zad integer NOT NULL,
    id_vyp integer NOT NULL
);


ALTER TABLE public."vypolnenie - zadanie" OWNER TO postgres;

--
-- Name: vypolnenie_id_vyp_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vypolnenie ALTER COLUMN id_vyp ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vypolnenie_id_vyp_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: xaracteristika; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.xaracteristika (
    id_xar integer NOT NULL,
    id_otchet integer NOT NULL,
    sorerzhanie text NOT NULL,
    date_polucheniya date NOT NULL,
    id_curator integer NOT NULL
);


ALTER TABLE public.xaracteristika OWNER TO postgres;

--
-- Name: xaracteristika_id_xar_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.xaracteristika ALTER COLUMN id_xar ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xaracteristika_id_xar_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zadanie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zadanie (
    id_zad integer NOT NULL,
    nazvamie_zad character varying(255) NOT NULL,
    type_zad character varying(50) NOT NULL,
    opisanie text NOT NULL,
    id_plan integer NOT NULL,
    date_sozdanie date NOT NULL,
    date_end date NOT NULL
);


ALTER TABLE public.zadanie OWNER TO postgres;

--
-- Name: zadanie_id_zad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zadanie ALTER COLUMN id_zad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zadanie_id_zad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zayavka_studenta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zayavka_studenta (
    id_zayavki integer NOT NULL,
    id_studenta integer NOT NULL,
    id_vakansiya integer NOT NULL,
    data_podachi date DEFAULT CURRENT_DATE NOT NULL,
    prioritet integer NOT NULL,
    status character varying(50) NOT NULL,
    urovnen_sovpadeniya double precision NOT NULL
);


ALTER TABLE public.zayavka_studenta OWNER TO postgres;

--
-- Name: zayavka_studenta_id_zayavki_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zayavka_studenta ALTER COLUMN id_zayavki ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zayavka_studenta_id_zayavki_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attestat-result-otchen attestat-result-otchen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."attestat-result-otchen"
    ADD CONSTRAINT "attestat-result-otchen_pkey" PRIMARY KEY (id_rec);


--
-- Name: curator curator_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curator
    ADD CONSTRAINT curator_pkey PRIMARY KEY (id_curator);


--
-- Name: etap_plana etap_plana_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etap_plana
    ADD CONSTRAINT etap_plana_pkey PRIMARY KEY (id_etap);


--
-- Name: kaf - practika kaf - practika_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."kaf - practika"
    ADD CONSTRAINT "kaf - practika_pkey" PRIMARY KEY (id_kafedra, id_practika);


--
-- Name: kafedra kafedra_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kafedra
    ADD CONSTRAINT kafedra_pkey PRIMARY KEY (id_kafedra);


--
-- Name: kom - kafedra kom - kafedra_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."kom - kafedra"
    ADD CONSTRAINT "kom - kafedra_pkey" PRIMARY KEY (id_kafedra, id_kom);


--
-- Name: komissiya komissiya_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komissiya
    ADD CONSTRAINT komissiya_pkey PRIMARY KEY (id_kom);


--
-- Name: kompetenciya kompetenciya_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kompetenciya
    ADD CONSTRAINT kompetenciya_pkey PRIMARY KEY (id_kompetenciya);


--
-- Name: kompetenciya_studenta kompetenciya_studenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kompetenciya_studenta
    ADD CONSTRAINT kompetenciya_studenta_pkey PRIMARY KEY (id_studenta, id_kompetencii);


--
-- Name: org - curator org - curator_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."org - curator"
    ADD CONSTRAINT "org - curator_pkey" PRIMARY KEY (id_curator, id_organization);


--
-- Name: org - practika org - practika_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."org - practika"
    ADD CONSTRAINT "org - practika_pkey" PRIMARY KEY (id_organization, id_practika);


--
-- Name: organization organization_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organization
    ADD CONSTRAINT organization_pkey PRIMARY KEY (id_organization);


--
-- Name: plan_praktiki plan_praktiki_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_praktiki
    ADD CONSTRAINT plan_praktiki_pkey PRIMARY KEY (id_plan);


--
-- Name: practika practika_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practika
    ADD CONSTRAINT practika_pkey PRIMARY KEY (id_practica);


--
-- Name: prepodavatel prepodavatel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prepodavatel
    ADD CONSTRAINT prepodavatel_pkey PRIMARY KEY (id_prepod);


--
-- Name: raspredelenie raspredelenie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raspredelenie
    ADD CONSTRAINT raspredelenie_pkey PRIMARY KEY (id_raspred);


--
-- Name: sovpadenie_po_kompetencii sovpadenie_po_kompetencii_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sovpadenie_po_kompetencii
    ADD CONSTRAINT sovpadenie_po_kompetencii_pkey PRIMARY KEY (id_sovp);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id_studenta);


--
-- Name: trebovanie_vakansii trebovanie_vakansii_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trebovanie_vakansii
    ADD CONSTRAINT trebovanie_vakansii_pkey PRIMARY KEY (id_vakansii, id_kompetencii);


--
-- Name: users users_login_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_login_key UNIQUE (login);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- Name: vakansiya vakansiya_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vakansiya
    ADD CONSTRAINT vakansiya_pkey PRIMARY KEY (id_vakansiya);


--
-- Name: vypolnenie - at-res-otch vypolnenie - at-res-otch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."vypolnenie - at-res-otch"
    ADD CONSTRAINT "vypolnenie - at-res-otch_pkey" PRIMARY KEY (id_rec, id_vyp);


--
-- Name: vypolnenie - zadanie vypolnenie - zadanie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."vypolnenie - zadanie"
    ADD CONSTRAINT "vypolnenie - zadanie_pkey" PRIMARY KEY (id_zad, id_vyp);


--
-- Name: vypolnenie vypolnenie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vypolnenie
    ADD CONSTRAINT vypolnenie_pkey PRIMARY KEY (id_vyp);


--
-- Name: xaracteristika xaracteristika_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xaracteristika
    ADD CONSTRAINT xaracteristika_pkey PRIMARY KEY (id_xar);


--
-- Name: zadanie zadanie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zadanie
    ADD CONSTRAINT zadanie_pkey PRIMARY KEY (id_zad);


--
-- Name: zayavka_studenta zayavka_studenta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zayavka_studenta
    ADD CONSTRAINT zayavka_studenta_pkey PRIMARY KEY (id_zayavki);


--
-- Name: attestat-result-otchen attestat-result-otchen_id_kom_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."attestat-result-otchen"
    ADD CONSTRAINT "attestat-result-otchen_id_kom_fkey" FOREIGN KEY (id_kom) REFERENCES public.komissiya(id_kom);


--
-- Name: curator curator_id_organization_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curator
    ADD CONSTRAINT curator_id_organization_fkey FOREIGN KEY (id_organization) REFERENCES public.organization(id_organization);


--
-- Name: etap_plana etap_plana_id_plan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etap_plana
    ADD CONSTRAINT etap_plana_id_plan_fkey FOREIGN KEY (id_plan) REFERENCES public.plan_praktiki(id_plan);


--
-- Name: kaf - practika kaf - practika_id_kafedra_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."kaf - practika"
    ADD CONSTRAINT "kaf - practika_id_kafedra_fkey" FOREIGN KEY (id_kafedra) REFERENCES public.kafedra(id_kafedra);


--
-- Name: kaf - practika kaf - practika_id_practika_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."kaf - practika"
    ADD CONSTRAINT "kaf - practika_id_practika_fkey" FOREIGN KEY (id_practika) REFERENCES public.practika(id_practica);


--
-- Name: kom - kafedra kom - kafedra_id_kafedra_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."kom - kafedra"
    ADD CONSTRAINT "kom - kafedra_id_kafedra_fkey" FOREIGN KEY (id_kafedra) REFERENCES public.kafedra(id_kafedra);


--
-- Name: kom - kafedra kom - kafedra_id_kom_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."kom - kafedra"
    ADD CONSTRAINT "kom - kafedra_id_kom_fkey" FOREIGN KEY (id_kom) REFERENCES public.komissiya(id_kom);


--
-- Name: kompetenciya_studenta kompetenciya_studenta_id_kompetencii_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kompetenciya_studenta
    ADD CONSTRAINT kompetenciya_studenta_id_kompetencii_fkey FOREIGN KEY (id_kompetencii) REFERENCES public.kompetenciya(id_kompetenciya);


--
-- Name: kompetenciya_studenta kompetenciya_studenta_id_studenta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kompetenciya_studenta
    ADD CONSTRAINT kompetenciya_studenta_id_studenta_fkey FOREIGN KEY (id_studenta) REFERENCES public.student(id_studenta);


--
-- Name: org - curator org - curator_id_curator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."org - curator"
    ADD CONSTRAINT "org - curator_id_curator_fkey" FOREIGN KEY (id_curator) REFERENCES public.curator(id_curator);


--
-- Name: org - curator org - curator_id_organization_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."org - curator"
    ADD CONSTRAINT "org - curator_id_organization_fkey" FOREIGN KEY (id_organization) REFERENCES public.organization(id_organization);


--
-- Name: org - practika org - practika_id_organization_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."org - practika"
    ADD CONSTRAINT "org - practika_id_organization_fkey" FOREIGN KEY (id_organization) REFERENCES public.organization(id_organization);


--
-- Name: org - practika org - practika_id_practika_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."org - practika"
    ADD CONSTRAINT "org - practika_id_practika_fkey" FOREIGN KEY (id_practika) REFERENCES public.practika(id_practica);


--
-- Name: plan_praktiki plan_praktiki_id_curator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_praktiki
    ADD CONSTRAINT plan_praktiki_id_curator_fkey FOREIGN KEY (id_curator) REFERENCES public.curator(id_curator);


--
-- Name: plan_praktiki plan_praktiki_id_practika_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_praktiki
    ADD CONSTRAINT plan_praktiki_id_practika_fkey FOREIGN KEY (id_practika) REFERENCES public.practika(id_practica);


--
-- Name: plan_praktiki plan_praktiki_id_prepod_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_praktiki
    ADD CONSTRAINT plan_praktiki_id_prepod_fkey FOREIGN KEY (id_prepod) REFERENCES public.prepodavatel(id_prepod);


--
-- Name: practika practika_id_curator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practika
    ADD CONSTRAINT practika_id_curator_fkey FOREIGN KEY (id_curator) REFERENCES public.curator(id_curator);


--
-- Name: practika practika_id_prepod_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practika
    ADD CONSTRAINT practika_id_prepod_fkey FOREIGN KEY (id_prepod) REFERENCES public.prepodavatel(id_prepod);


--
-- Name: prepodavatel prepodavatel_id_kafedra_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prepodavatel
    ADD CONSTRAINT prepodavatel_id_kafedra_fkey FOREIGN KEY (id_kafedra) REFERENCES public.kafedra(id_kafedra);


--
-- Name: raspredelenie raspredelenie_id_curator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raspredelenie
    ADD CONSTRAINT raspredelenie_id_curator_fkey FOREIGN KEY (id_curator) REFERENCES public.curator(id_curator);


--
-- Name: raspredelenie raspredelenie_id_prepod_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raspredelenie
    ADD CONSTRAINT raspredelenie_id_prepod_fkey FOREIGN KEY (id_prepod) REFERENCES public.prepodavatel(id_prepod);


--
-- Name: raspredelenie raspredelenie_id_student_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raspredelenie
    ADD CONSTRAINT raspredelenie_id_student_fkey FOREIGN KEY (id_student) REFERENCES public.student(id_studenta);


--
-- Name: raspredelenie raspredelenie_id_vacansiya_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raspredelenie
    ADD CONSTRAINT raspredelenie_id_vacansiya_fkey FOREIGN KEY (id_vacansiya) REFERENCES public.vakansiya(id_vakansiya);


--
-- Name: raspredelenie raspredelenie_id_zayavka_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raspredelenie
    ADD CONSTRAINT raspredelenie_id_zayavka_fkey FOREIGN KEY (id_zayavka) REFERENCES public.zayavka_studenta(id_zayavki);


--
-- Name: sovpadenie_po_kompetencii sovpadenie_po_kompetencii_id_kompetenciya_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sovpadenie_po_kompetencii
    ADD CONSTRAINT sovpadenie_po_kompetencii_id_kompetenciya_fkey FOREIGN KEY (id_kompetenciya) REFERENCES public.kompetenciya(id_kompetenciya);


--
-- Name: sovpadenie_po_kompetencii sovpadenie_po_kompetencii_id_zayavki_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sovpadenie_po_kompetencii
    ADD CONSTRAINT sovpadenie_po_kompetencii_id_zayavki_fkey FOREIGN KEY (id_zayavki) REFERENCES public.zayavka_studenta(id_zayavki);


--
-- Name: student student_id_kafedra_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_id_kafedra_fkey FOREIGN KEY (id_kafedra) REFERENCES public.kafedra(id_kafedra);


--
-- Name: trebovanie_vakansii trebovanie_vakansii_id_kompetencii_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trebovanie_vakansii
    ADD CONSTRAINT trebovanie_vakansii_id_kompetencii_fkey FOREIGN KEY (id_kompetencii) REFERENCES public.kompetenciya(id_kompetenciya);


--
-- Name: trebovanie_vakansii trebovanie_vakansii_id_vakansii_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trebovanie_vakansii
    ADD CONSTRAINT trebovanie_vakansii_id_vakansii_fkey FOREIGN KEY (id_vakansii) REFERENCES public.vakansiya(id_vakansiya);


--
-- Name: users users_id_curator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_curator_fkey FOREIGN KEY (id_curator) REFERENCES public.curator(id_curator) ON DELETE SET NULL;


--
-- Name: users users_id_prepod_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_prepod_fkey FOREIGN KEY (id_prepod) REFERENCES public.prepodavatel(id_prepod) ON DELETE SET NULL;


--
-- Name: users users_id_studenta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_studenta_fkey FOREIGN KEY (id_studenta) REFERENCES public.student(id_studenta) ON DELETE SET NULL;


--
-- Name: vakansiya vakansiya_id_organization_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vakansiya
    ADD CONSTRAINT vakansiya_id_organization_fkey FOREIGN KEY (id_organization) REFERENCES public.organization(id_organization) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: vypolnenie - at-res-otch vypolnenie - at-res-otch_id_rec_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."vypolnenie - at-res-otch"
    ADD CONSTRAINT "vypolnenie - at-res-otch_id_rec_fkey" FOREIGN KEY (id_rec) REFERENCES public."attestat-result-otchen"(id_rec);


--
-- Name: vypolnenie - at-res-otch vypolnenie - at-res-otch_id_vyp_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."vypolnenie - at-res-otch"
    ADD CONSTRAINT "vypolnenie - at-res-otch_id_vyp_fkey" FOREIGN KEY (id_vyp) REFERENCES public.vypolnenie(id_vyp);


--
-- Name: vypolnenie - zadanie vypolnenie - zadanie_id_vyp_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."vypolnenie - zadanie"
    ADD CONSTRAINT "vypolnenie - zadanie_id_vyp_fkey" FOREIGN KEY (id_vyp) REFERENCES public.vypolnenie(id_vyp);


--
-- Name: vypolnenie - zadanie vypolnenie - zadanie_id_zad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."vypolnenie - zadanie"
    ADD CONSTRAINT "vypolnenie - zadanie_id_zad_fkey" FOREIGN KEY (id_zad) REFERENCES public.zadanie(id_zad);


--
-- Name: vypolnenie vypolnenie_id_zad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vypolnenie
    ADD CONSTRAINT vypolnenie_id_zad_fkey FOREIGN KEY (id_zad) REFERENCES public.zadanie(id_zad);


--
-- Name: xaracteristika xaracteristika_id_curator_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xaracteristika
    ADD CONSTRAINT xaracteristika_id_curator_fkey FOREIGN KEY (id_curator) REFERENCES public.curator(id_curator);


--
-- Name: xaracteristika xaracteristika_id_otchet_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xaracteristika
    ADD CONSTRAINT xaracteristika_id_otchet_fkey FOREIGN KEY (id_otchet) REFERENCES public."attestat-result-otchen"(id_rec);


--
-- Name: zadanie zadanie_id_plan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zadanie
    ADD CONSTRAINT zadanie_id_plan_fkey FOREIGN KEY (id_plan) REFERENCES public.plan_praktiki(id_plan);


--
-- Name: zayavka_studenta zayavka_studenta_id_studenta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zayavka_studenta
    ADD CONSTRAINT zayavka_studenta_id_studenta_fkey FOREIGN KEY (id_studenta) REFERENCES public.student(id_studenta);


--
-- Name: zayavka_studenta zayavka_studenta_id_vakansiya_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zayavka_studenta
    ADD CONSTRAINT zayavka_studenta_id_vakansiya_fkey FOREIGN KEY (id_vakansiya) REFERENCES public.vakansiya(id_vakansiya);


--
-- PostgreSQL database dump complete
--

\unrestrict g7gNBYudD88oOAbyd4TewXfwYb4lTpeYszAN9E0AKTV81f0YVqg6xrygFgRtd9Q

